language: node_js
node_js:
  - "node"

install:
  - npm install

script:
  - npm run build:prod

branches:
  only:
    - master

deploy:
 provider: pages
 skip_cleanup: true
 keep_history: true
 github_token: $GITHUB_TOKEN
 local_dir: ./dist/
 on:
   branch: master