export const nameVal = {
  大剑: 'GreatSword',
  太刀: 'LongSword',
  单手剑: 'SwordAndShield',
  双剑: 'DualBlades',
  大锤: 'Hammer',
  狩猎笛: 'HuntingHorn',
  长枪: 'Lance',
  铳枪: 'Gunlance',
  斩击斧: 'SwitchAxe',
  充能斧: 'ChargeBlade',
  操虫棍: 'InsectGlaive',
  轻弩: 'LightBowgun',
  重弩: 'HeavyBowgun',
  弓: 'Bow',
  水: 'fire',
  火: 'water',
  雷: 'thunder',
  冰: 'ice',
  龙: 'dragon',
  毒: 'poison',
  爆破: 'blast',
  睡眠: 'sleep',
  麻痹: 'paralysis'
}
