export const nameVal = {
  大剑: 'GreatSword',
  太刀: 'LongSword',
  单手剑: 'SwordAndShield',
  双剑: 'DualBlades',
  大锤: 'Hammer',
  狩猎笛: 'HuntingHorn',
  长枪: 'Lance',
  铳枪: 'Gunlance',
  斩击斧: 'SwitchAxe',
  充能斧: 'ChargeBlade',
  操虫棍: 'InsectGlaive',
  轻弩: 'LightBowgun',
  重弩: 'HeavyBowgun',
  弓: 'Bow',
  火: 'Fire',
  水: 'Water',
  雷: 'Thunder',
  冰: 'Ice',
  龙: 'Dragon',
  毒: 'Poison',
  爆破: 'Blast',
  睡眠: 'Sleep',
  麻痹: 'Paralysis'
}
